export const countryNameFromCode = {
  "AM":	"Armenia",
  "AP":	"African Regional",
  "AR":	"Argentina",
  "AT":	"Austria",
  "AU":	"Australia",
  "BA":	"Bosnia and Herzegovina",
  "BE":	"Belgium",
  "BG":	"Bulgaria",
  "BR":	"Brazil",
  "BY":	"Belarus",
  "CA":	"Canada",
  "CH":	"Switzerland",
  "CL":	"Chile",
  "CN":	"China",
  "CO":	"Colombia",
  "CR":	"Costa Rica",
  "CS":	"Czechoslovakia",
  "CU":	"Cuba",
  "CY":	"Cyprus",
  "CZ":	"Czech Republic",
  "DD":	"German Democratic Republic ",
  "DE":	"Germany",
  "DK":	"Denmark",
  "DO":	"Dominican Republic",
  "DZ":	"Algeria",
  "EA":	"Eurasian Patent Organization",
  "EC":	"Ecuador",
  "EE":	"Estonia",
  "EG":	"Egypt",
  "EM":	"European Union",
  "EP":	"European Patent",
  "ES":	"Spain",
  "FI":	"Finland",
  "FR":	"France",
  "GB":	"United Kingdom",
  "GC":	"Gulf Cooperation Council",
  "GE":	"Georgia",
  "GR":	"Greece",
  "GT":	"Guatemala",
  "HK":	"Hong Kong",
  "HN":	"Honduras",
  "HR":	"Croatia",
  "HU":	"Hungary",
  "ID":	"Indonesia",
  "IE":	"Ireland",
  "IL":	"Israel",
  "IN":	"India",
  "IS":	"Iceland",
  "IT":	"Italy",
  "JO":	"Jordan",
  "JP":	"Japan",
  "KE":	"Kenya",
  "KG":	"Kyrgyzstan",
  "KR":	"Korea (South)",
  "KZ":	"Kazakhstan",
  "LT":	"Lithuania",
  "LU":	"Luxembourg",
  "LV":	"Latvia",
  "MA":	"Morocco",
  "MC":	"Monaco",
  "MD":	"Republic of Moldova",
  "ME":	"Montenegro",
  "MN":	"Mongolia",
  "MO":	"Macao",
  "MT":	"Malta",
  "MW":	"Malawi",
  "MX":	"Mexico",
  "MY":	"Malaysia",
  "NI":	"Nicaragua",
  "NL":	"Netherlands",
  "NO":	"Norway",
  "NZ":	"New Zealand",
  "OA":	"African Intellectual Property Organization",
  "PA":	"Panama",
  "PE":	"Peru",
  "PH":	"Philippines",
  "PL":	"Poland",
  "PT":	"Portugal",
  "RO":	"Romania",
  "RS":	"Serbia",
  "RU":	"Russian Federation",
  "SA":	"Saudi Arabia",
  "SE":	"Sweden",
  "SG":	"Singapore",
  "SI":	"Slovenia",
  "SK":	"Slovakia",
  "SM":	"San Marino",
  "SU":	"Soviet Union (USSR)",
  "SV":	"El Salvador",
  "TH":	"Thailand",
  "TJ":	"Tajikistan",
  "TN":	"Tunisia",
  "TR":	"Turkey",
  "TT":	"Trinidad and Tobago",
  "TW":	"Chinese Taipei",
  "UA":	"Ukraine",
  "US":	"United States of America",
  "UY":	"Uruguay",
  "UZ":	"Uzbekistan",
  "VN":	"Viet Nam",
  "WO":	"WIPO",
  "YU":	"Yugoslavia / Serbia and Montenegro",
  "ZA":	"South Africa",
  "ZM":	"Zambia",
  "ZW":	"Zimbabwe"
};
