export const languageFromCode = {
  "EN": "English",
  "FR": "French",
  "DE": "German",
  "ES": "Spanish",
  "AR": "Arabic",
  "DA": "Danish",
  "FI": "Finnish",
  "HE": "Hebrew",
  "HR": "Croatian",
  "HU": "Hungarian",
  "IT": "Italian",
  "JA": "Japanese",
  "KO": "Kongo",
  "LT": "Lithuanian",
  "NL": "Dutch",
  "NO": "Norwegian",
  "PL": "Polish",
  "PT": "Portuguese",
  "RO": "Romansh",
  "RU": "Russian",
  "SL": "Slovenian",
  "SR": "Serbian",
  "SV": "Swedish",
  "TR": "Turkish",
  "ZH": "Chinese"
};
